window.FOCUS_UNITS = [
  {
    id: 1,
    name: "Unit 1",
    title: "探索文明",
    scene: "plain",
    goal: 10,
    words: [
      "dinosaur", "intelligent", "talented", "artistic", "perhaps", "notebook", "vehicle",
      "prehistoric", "completely", "original", "birth", "suffering", "artist", "death",
      "whole", "piece", "editor", "organize", "order", "record", "general education",
      "go back a long way", "be similar to", "alphabetical order", "play an important role",
      "die out", "a type of", "be related to"
    ]
  },
  {
    id: 2,
    name: "Unit 2",
    title: "挑战棋盘",
    scene: "river",
    goal: 10,
    words: [
      "flight", "schedule", "everywhere", "challenge", "prize", "promise", "chessboard",
      "silver", "reply", "hesitation", "wonder", "agree", "percent", "currently", "check",
      "budget", "province", "sharply", "count", "system", "symbol", "represent", "exactly",
      "flight schedule", "price tag", "for a moment", "without hesitation", "go up",
      "go down", "write down", "instead of"
    ]
  },
  {
    id: 3,
    name: "Unit 3",
    title: "未来网络",
    scene: "mountain",
    goal: 12,
    words: [
      "network", "flood", "multimedia", "expert", "mobile", "payment", "warn", "treatment",
      "data", "company", "traffic", "flow", "smoothly", "laptop", "screen", "weight",
      "digital", "social", "message", "interview", "positive", "negative", "effect",
      "opinion", "novel", "comment", "basis", "microprocessor", "microchip", "major",
      "breakthrough", "electronic", "software", "app", "era", "download", "tiny",
      "connect to", "bring big changes to", "mobile payment", "take...for example",
      "rubbish bin", "social media", "in person", "the general public"
    ]
  },
  {
    id: 4,
    name: "Unit 4",
    title: "发明工坊",
    scene: "desert",
    goal: 12,
    words: [
      "balloon", "wheel", "central", "although", "attach", "pull", "international", "path",
      "technique", "depend", "doubt", "personally", "prediction", "statement", "benefit",
      "wing", "distance", "petrol", "avoid", "anywhere", "notice", "type", "mixture",
      "heat", "press", "metal", "steam locomotive", "crewed spacecraft", "on foot",
      "a number of", "take place", "for instance", "large amounts of", "international trade",
      "depend on", "3D printer", "without doubt", "of all time", "make fun of", "traffic jam"
    ]
  },
  {
    id: 5,
    name: "Unit 5",
    title: "异国旅程",
    scene: "forest",
    goal: 10,
    words: [
      "exchange", "nervous", "grateful", "chopstick", "tour", "tai chi", "yet",
      "independent", "content", "feeling", "shock", "foreign", "confused", "anxious",
      "phase", "honeymoon", "unfamiliar", "homesick", "lonely", "deal", "expect",
      "situation", "accept", "adaptation", "Beijing opera", "host family", "make its way",
      "culture shock", "deal with", "feel at home"
    ]
  },
  {
    id: 6,
    name: "Unit 6",
    title: "木马奇袭",
    scene: "ruins",
    goal: 10,
    words: [
      "author", "remains", "locate", "soldier", "captain", "empty", "victory", "joke",
      "midnight", "except", "hide", "secretly", "enter", "succeed", "trick", "fight",
      "beat", "pretend", "enemy", "fail", "therefore", "within", "fill", "towards",
      "attack", "fog", "make jokes about", "succeed in", "be tired of", "go on board",
      "be jealous of", "be full of"
    ]
  },
  {
    id: 7,
    name: "Unit 7",
    title: "记忆训练",
    scene: "plain",
    goal: 10,
    words: [
      "regularly", "repeat", "note", "visual", "mentally", "link", "list", "especially",
      "diet", "maintain", "nut", "relax", "stressed", "tend", "normal", "loss", "fork",
      "onion", "ant", "context", "image", "sense", "summary", "contain", "particular",
      "chemistry", "flash card", "make a point of doing something", "last but not least",
      "natural disaster", "figure out"
    ]
  },
  {
    id: 8,
    name: "Unit 8",
    title: "忠犬选择",
    scene: "river",
    goal: 10,
    words: [
      "faithful", "hold", "responsible", "awake", "flat", "choice", "advise", "cause",
      "complain", "litter", "unlikely", "relieve", "indoors", "magical", "wealth",
      "queen", "servant", "pride", "among", "relationship", "grow up", "care for",
      "in short", "have no choice but to do", "lie around", "complain about", "in addition",
      "catch the eye of somebody"
    ]
  }
];

window.FOCUS_MEANINGS = {
  "dinosaur": "恐龙",
  "intelligent": "有才智的；聪明的",
  "talented": "有才能的；有天赋的",
  "artistic": "艺术的；有艺术天赋的",
  "vehicle": "交通工具；车辆",
  "prehistoric": "史前的",
  "completely": "完全地；彻底地",
  "original": "最早的；原创的",
  "suffering": "痛苦；苦难",
  "editor": "编辑",
  "organize": "组织；安排",
  "general education": "通识教育",
  "go back a long way": "有很长的历史",
  "be similar to": "与……相似",
  "alphabetical order": "字母顺序",
  "play an important role": "起重要作用",
  "die out": "灭绝；消失",
  "a type of": "一种",
  "be related to": "与……相关",
  "flight": "航班；飞行",
  "schedule": "日程安排；时间表",
  "chessboard": "棋盘",
  "hesitation": "犹豫",
  "percent": "百分之……",
  "currently": "目前；现在",
  "province": "省",
  "sharply": "急剧地；尖锐地",
  "system": "系统",
  "represent": "代表；象征",
  "flight schedule": "航班时刻表",
  "price tag": "价签",
  "for a moment": "一会儿；片刻",
  "without hesitation": "毫不犹豫",
  "go up": "上升",
  "go down": "下降",
  "write down": "写下；记下",
  "instead of": "代替；而不是",
  "network": "网络",
  "multimedia": "多媒体",
  "payment": "支付；付款",
  "treatment": "治疗；处理",
  "data": "数据；资料",
  "flow": "流动",
  "smoothly": "顺利地；平稳地",
  "comment": "评论；意见",
  "basis": "基础；根据",
  "microprocessor": "微处理器",
  "microchip": "微芯片",
  "major": "主要的；重大的",
  "breakthrough": "突破",
  "software": "软件",
  "connect to": "连接到",
  "bring big changes to": "给……带来巨大变化",
  "mobile payment": "移动支付",
  "take...for example": "以……为例",
  "rubbish bin": "垃圾桶",
  "social media": "社交媒体",
  "in person": "亲自；当面",
  "the general public": "公众",
  "attach": "系上；贴上；附上",
  "path": "小路；路径",
  "technique": "技术；技巧",
  "personally": "就个人而言；亲自",
  "prediction": "预测",
  "statement": "陈述；声明",
  "distance": "距离",
  "petrol": "汽油",
  "type": "类型；种类",
  "mixture": "混合物",
  "metal": "金属",
  "steam locomotive": "蒸汽机车",
  "crewed spacecraft": "载人宇宙飞船",
  "on foot": "步行",
  "a number of": "许多；若干",
  "take place": "发生；举行",
  "for instance": "例如",
  "large amounts of": "大量的",
  "international trade": "国际贸易",
  "depend on": "依靠；取决于",
  "3D printer": "3D 打印机",
  "without doubt": "毫无疑问",
  "of all time": "有史以来",
  "make fun of": "取笑；嘲弄",
  "traffic jam": "交通堵塞",
  "exchange": "交换；交流",
  "grateful": "感激的",
  "chopstick": "筷子",
  "tai chi": "太极",
  "independent": "独立的",
  "content": "内容",
  "confused": "困惑的",
  "anxious": "焦虑的；担心的",
  "phase": "阶段；时期",
  "honeymoon": "蜜月",
  "unfamiliar": "不熟悉的",
  "homesick": "想家的",
  "adaptation": "适应；改编",
  "host family": "寄宿家庭",
  "make its way": "前往；行进",
  "culture shock": "文化冲击",
  "deal with": "处理；应对",
  "feel at home": "感觉自在",
  "author": "作者",
  "remains": "遗迹；遗体",
  "locate": "位于；找出位置",
  "captain": "首领；船长；队长",
  "midnight": "午夜",
  "secretly": "秘密地",
  "trick": "计谋；把戏",
  "pretend": "假装",
  "towards": "朝；向",
  "make jokes about": "拿……开玩笑",
  "succeed in": "成功做到",
  "be tired of": "厌倦",
  "go on board": "上船；登上",
  "be jealous of": "嫉妒",
  "be full of": "充满",
  "regularly": "有规律地；定期地",
  "visual": "视觉的",
  "mentally": "精神上；脑力上",
  "link": "连接；联系",
  "maintain": "保持；维持",
  "nut": "坚果",
  "stressed": "焦虑不安的；有压力的",
  "tend": "往往会；倾向于",
  "context": "上下文；语境",
  "image": "图像；形象",
  "summary": "总结；概要",
  "contain": "包含；含有",
  "particular": "特定的；特别的",
  "flash card": "识字卡；抽认卡",
  "make a point of doing something": "特意做某事",
  "last but not least": "最后但同样重要的是",
  "natural disaster": "自然灾害",
  "figure out": "弄清楚；算出",
  "faithful": "忠诚的",
  "complain": "抱怨",
  "unlikely": "不大可能的",
  "relieve": "减轻；缓解",
  "indoors": "在室内",
  "magical": "神奇的；有魔力的",
  "servant": "仆人",
  "grow up": "长大；成长",
  "care for": "照顾；喜欢",
  "in short": "简言之",
  "have no choice but to do": "除了做……别无选择",
  "lie around": "闲躺；到处乱放",
  "complain about": "抱怨",
  "in addition": "另外；此外",
  "catch the eye of somebody": "吸引某人的注意"
};
